"""Executor: convierte un plan en un script Python que corre dentro de Blender.

Reusa la librería local `kernel_scripts` (copia del paquete del monorepo).
El plan llega del server como lista de {tool, args}. Aquí lo serializamos
a un script Python autocontenido que Blender ejecuta con `--background`.

Estructura del plan:
  [
    {"tool": "set_active_view_layer", "args": {"scene": "...", "view_layer_name": "sweaty"}},
    {"tool": "swap_label", "args": {"scene": "...", "png_path": "...", "material_name": "Label"}},
    {"tool": "set_cap_color", "args": {"scene": "...", "rgb_hex": "#000000FF"}},
    {"tool": "render_one_view", "args": {"scene": "...", "output_path": "..."}}
  ]
"""

from __future__ import annotations

import json
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path


@dataclass
class StepResult:
    tool: str
    success: bool
    result: dict | None = None
    error: str | None = None


@dataclass
class ExecuteResult:
    success: bool
    duration_seconds: float
    stdout: str
    stderr: str
    outputs: list[str]
    step_results: list[StepResult]
    steps_executed: int
    steps_total: int
    failed_step: dict | None = None


def _runner_script(plan_json: str, log_path: str, scripts_src: str) -> str:
    """Genera el script Python que ejecuta el plan dentro de Blender.

    Espejo del que genera apps/web/src/lib/executor/blender.ts en el monorepo.
    """
    plan_literal = json.dumps(plan_json)  # double-encoded para json.loads en Python
    log_literal = json.dumps(log_path)
    scripts_literal = json.dumps(scripts_src)
    return f"""# Auto-generated by Kernel Renders Agent.
import json, sys, traceback
from pathlib import Path
import bpy

sys.path.insert(0, {scripts_literal})

TOOLS = {{}}

def _register_tools():
    from kernel_scripts.swap_label import run_swap_label
    from kernel_scripts.set_cap_color import run_set_cap_color
    from kernel_scripts.set_view_layer import run_set_active_view_layer
    from kernel_scripts.inspect_scene import run_inspect_scene
    from kernel_scripts.render_views import run_render_one_view, run_render_all_cameras, run_render_rotations
    TOOLS["swap_label"] = run_swap_label
    TOOLS["set_cap_color"] = run_set_cap_color
    TOOLS["set_active_view_layer"] = run_set_active_view_layer
    TOOLS["inspect_scene"] = run_inspect_scene
    TOOLS["render_one_view"] = run_render_one_view
    TOOLS["render_all_cameras"] = run_render_all_cameras
    TOOLS["render_rotations"] = run_render_rotations


def main():
    plan = json.loads({plan_literal})
    log = {{"outputs": [], "step_results": [], "steps_executed": 0, "failed_step": None}}
    log_path = Path({log_literal})

    try:
        _register_tools()
    except Exception as e:
        log["failed_step"] = {{"index": -1, "tool": "_import", "error": str(e)}}
        log_path.write_text(json.dumps(log))
        sys.exit(2)

    if not plan:
        log["failed_step"] = {{"index": -1, "tool": "_setup", "error": "plan vacio"}}
        log_path.write_text(json.dumps(log))
        sys.exit(1)

    first_scene = plan[0].get("args", {{}}).get("scene")
    if not first_scene or not Path(first_scene).exists():
        log["failed_step"] = {{"index": -1, "tool": "_setup", "error": f"Escena no existe: {{first_scene}}"}}
        log_path.write_text(json.dumps(log))
        sys.exit(1)

    print(f"[setup] Cargando escena: {{first_scene}}", flush=True)
    bpy.ops.wm.open_mainfile(filepath=str(first_scene))

    # Habilitar GPU para Cycles si esta disponible
    try:
        cycles_prefs = bpy.context.preferences.addons["cycles"].preferences
        for backend in ("OPTIX", "CUDA", "HIP", "ONEAPI"):
            try:
                cycles_prefs.compute_device_type = backend
                cycles_prefs.get_devices()
                devices = [d for d in cycles_prefs.devices if d.type != "CPU"]
                if devices:
                    for d in cycles_prefs.devices:
                        d.use = d.type != "CPU"
                    print(f"[setup] GPU backend={{backend}} devices={{[d.name for d in devices]}}", flush=True)
                    if bpy.context.scene.render.engine == "CYCLES":
                        bpy.context.scene.cycles.device = "GPU"
                    break
            except (TypeError, AttributeError):
                continue
    except (KeyError, AttributeError):
        pass

    # Relink texturas faltantes preservando las packed
    def _is_truly_missing(img):
        if img.source != "FILE" or not img.filepath:
            return False
        if img.packed_file is not None:
            return False
        return not Path(bpy.path.abspath(img.filepath)).exists()

    scene_dir = str(Path(first_scene).parent)
    missing_before = [img.name for img in bpy.data.images if _is_truly_missing(img)]
    if missing_before:
        print(f"[setup] Textures faltantes: {{missing_before}}", flush=True)
        try:
            bpy.ops.file.find_missing_files(directory=scene_dir)
        except Exception as e:
            print(f"  find_missing_files: {{e}}", flush=True)

    for i, step in enumerate(plan):
        tool_name = step["tool"]
        args = step["args"]
        print(f"[step {{i+1}}/{{len(plan)}}] {{tool_name}}", flush=True)
        fn = TOOLS.get(tool_name)
        if fn is None:
            log["failed_step"] = {{"index": i, "tool": tool_name, "error": "unknown tool"}}
            break
        try:
            result = fn(**args)
            if isinstance(result, dict):
                if result.get("outputs") and isinstance(result["outputs"], list):
                    log["outputs"].extend(str(p) for p in result["outputs"])
                elif result.get("output_path"):
                    log["outputs"].append(str(result["output_path"]))
                try:
                    json.dumps(result)
                    log["step_results"].append({{"tool": tool_name, "result": result}})
                except (TypeError, ValueError):
                    log["step_results"].append({{"tool": tool_name, "result": {{"success": True, "note": "no serializable"}}}})
            log["steps_executed"] += 1
        except Exception as e:
            log["failed_step"] = {{
                "index": i, "tool": tool_name,
                "error": f"{{type(e).__name__}}: {{e}}\\n{{traceback.format_exc()}}",
            }}
            break

    log_path.write_text(json.dumps(log))
    if log["failed_step"]:
        sys.exit(1)


main()
"""


def _expand_placeholders(plan: list[dict], output_dir: str) -> list[dict]:
    """Reemplaza {OUTPUT_DIR} en los args del plan con el output_dir local.

    La UI manda paths con {OUTPUT_DIR} en lugar de un path absoluto, así el
    plan es portable entre máquinas (cada agent expande con su config local).
    """
    if not output_dir:
        return plan
    out: list[dict] = []
    for step in plan:
        new_args = {}
        for k, v in (step.get("args") or {}).items():
            if isinstance(v, str) and "{OUTPUT_DIR}" in v:
                new_args[k] = v.replace("{OUTPUT_DIR}", output_dir)
            else:
                new_args[k] = v
        out.append({**step, "args": new_args})
    return out


def execute_plan(
    plan: list[dict],
    blender_bin: str,
    work_dir: Path | None = None,
    on_step_done: callable | None = None,
    output_dir: str = "",
) -> ExecuteResult:
    """Ejecuta el plan completo lanzando Blender headless.

    Args:
        plan: lista de {tool, args}
        blender_bin: ruta absoluta a blender.exe
        work_dir: dir para script temp y log. Si None, usa tmpdir.
        on_step_done: callback opcional invocado al detectar "[step N/M]" en stdout.
                      Signature: (step_index, total, message) -> None
    """
    import time

    work_dir = work_dir or Path(tempfile.mkdtemp(prefix="kernel-agent-"))
    work_dir.mkdir(parents=True, exist_ok=True)

    # Expandir {OUTPUT_DIR} con el output_dir configurado del agent
    plan = _expand_placeholders(plan, output_dir)

    # Descarga URLs de assets (de Supabase Storage) a tempfiles antes de
    # generar el script de Blender, que asume rutas locales.
    from .asset_materializer import materialize_plan_assets
    plan = materialize_plan_assets(plan, work_dir / "assets")

    script_path = work_dir / "_run.py"
    log_path = work_dir / "_outputs.json"
    plan_json = json.dumps(plan)

    # sys.path debe contener el PADRE de kernel_scripts/ (no la carpeta misma)
    # para que `from kernel_scripts.X import Y` lo encuentre como paquete.
    # __file__ = src/kernel_agent/executor.py → parent.parent = src/
    scripts_src = str(Path(__file__).resolve().parent.parent)
    if not (Path(scripts_src) / "kernel_scripts" / "__init__.py").exists():
        raise RuntimeError(
            f"kernel_scripts package not found under {scripts_src}. "
            "Reinstala el agent con `pip install -e .` desde la raíz del repo."
        )

    script_path.write_text(_runner_script(plan_json, str(log_path), scripts_src), encoding="utf-8")

    start = time.time()
    cmd = [blender_bin, "--background", "--python", str(script_path), "--python-exit-code", "1"]

    stdout_lines: list[str] = []
    stderr_lines: list[str] = []

    proc = subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        bufsize=1,
    )

    # Lee stdout línea por línea para detectar "[step N/M]" y disparar callback
    assert proc.stdout is not None
    total_steps = len(plan)
    last_step_reported = -1
    for line in proc.stdout:
        stdout_lines.append(line)
        if on_step_done and "[step " in line:
            try:
                # "[step 1/4] swap_label" → extrae 1 y 4
                inside = line.split("[step ", 1)[1].split("]", 1)[0]
                cur_str, total_str = inside.split("/")
                cur = int(cur_str)
                if cur > last_step_reported:
                    last_step_reported = cur
                    msg = line.split("]", 1)[1].strip() if "]" in line else ""
                    on_step_done(cur, int(total_str), msg)
            except (ValueError, IndexError):
                pass
    proc.wait()
    assert proc.stderr is not None
    stderr_lines = proc.stderr.read().splitlines()

    duration = time.time() - start
    stdout = "".join(stdout_lines)
    stderr = "\n".join(stderr_lines)

    # Parse del log JSON
    outputs: list[str] = []
    step_results: list[StepResult] = []
    failed_step = None
    steps_executed = 0
    if log_path.exists():
        try:
            data = json.loads(log_path.read_text(encoding="utf-8"))
            outputs = data.get("outputs", [])
            for sr in data.get("step_results", []):
                step_results.append(StepResult(tool=sr.get("tool"), success=True, result=sr.get("result")))
            steps_executed = data.get("steps_executed", 0)
            failed_step = data.get("failed_step")
        except (json.JSONDecodeError, OSError):
            pass

    return ExecuteResult(
        success=proc.returncode == 0 and failed_step is None,
        duration_seconds=round(duration, 2),
        stdout=stdout,
        stderr=stderr,
        outputs=outputs,
        step_results=step_results,
        steps_executed=steps_executed,
        steps_total=total_steps,
        failed_step=failed_step,
    )
